model:
    name: two_view_pipeline
    extractor:
        name: lines.deeplsd
        model_conf:
            detect_lines: True
            line_detection_params:
                merge: False
                grad_nfa: False
                filtering: strict  # True
                faster_lsd: True

    matcher:
        name: matchers.line_matcher
        line_dist: orth
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: opencv
            ransac_th: 0.5
    hpatches_lines:
        data:
            preprocessing:
                side: long
                resize: 800
        use_points: False
        use_lines: True
