model:
    name: two_view_pipeline
    extractor:
      name: extractors.aliked
      max_num_keypoints: 2048
      detection_threshold: 0.0
    matcher:
      name: matchers.lightglue_pretrained
      features: aliked
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
