defaults:
  - model: two_view_pipeline
  - model@model.extractor: extractor/aliked
  - model@model.matcher: matcher/lightglue_pretrained
  - _self_

model:
    matcher:
      features: aliked
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
