defaults:
    - lightglue_homography
    - model@model.extractor: extractor/disk_kornia
    - _self_

model:
    extractor:
        max_num_keypoints: 512
        force_num_keypoints: True
        trainable: False
    matcher:
        input_dim: 128
