defaults:
    - lightglue_megadepth
    - model@model.extractor: extractor/disk_kornia
    - _self_

data:
    load_features:
        do: false  # enable this if you have cached predictions
        path: exports/megadepth-undist-depth-r1024_DISK-k2048-nms5/{scene}.h5
        padding_length: 2048
        padding_fn: pad_local_features
model:
    extractor:
        max_num_keypoints: 2048
        force_num_keypoints: True
        detection_threshold: 0.0
        trainable: False
    matcher:
        input_dim: 128
