model:
    name: two_view_pipeline
    extractor:
        name: null
    matcher:
        name: gluefactory_nonfree.imcui
        zoo_name: loftr
        detection_threshold: 0.015
        match_threshold: 0.0
        max_num_keypoints: 1000000  # do not filter by default.
benchmarks:
    megadepth1500:
    hpatches:
        model:
            matcher:
                max_num_keypoints: 1024  # overwrite config above
    scannet1500:
