defaults:
    - data: homographies
    - model: two_view_pipeline
    - model@model.matcher: matcher/lightglue
    - model@model.ground_truth: matcher/homography_matcher
    - _self_
data:
    batch_size: 128
train:
    seed: 0
    epochs: 40
    log_every_iter: 100
    eval_every_iter: 500
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
benchmarks:
    hpatches:
        eval:
            estimator: opencv
