model:
    name: two_view_pipeline
    extractor:
        name: null # Set this for sparse matching
    matcher:
        name: roma
        weights: outdoor
        sample_num_matches: 10000
        internal_hw: [630, 630]
        upsample_preds: true
        # output_hw: [1344, 1344]
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                resize: 1024
        model:
            matcher:
                internal_hw: [630, 630]  # > 644 yields MAGMA warning, official: 672
                output_hw: [1344, 1344]
                sample_num_matches: 5000
        eval:
            estimator: [opencv, poselib]
    scannet1500:
        model:
            matcher:
                weights: indoor
                sample_num_matches: 5000
        eval:
            estimator: [poselib,opencv]
            ransac_th: -1
