defaults:
    - lightglue_megadepth
    - model@model.extractor: extractor/sift
    - _self_

data:
    load_features:
        do: false  # enable this if you have cached predictions
        path: exports/megadepth-undist-depth-r1024_pycolmap_SIFTGPU-nms3-fixed-k2048/{scene}.h5
        padding_length: 2048
        padding_fn: pad_local_features
        data_keys: ["keypoints", "keypoint_scores", "descriptors", "oris", "scales"]
model:
    extractor:
        max_num_keypoints: 2048
        force_num_keypoints: True
        nms_radius: 3
        trainable: False
    matcher:
        add_scale_ori: true
        input_dim: 128
benchmarks:
    megadepth1500:
        model:
            extractor:
                nms_radius: 0
    hpatches:
        model:
            extractor:
                max_num_keypoints: 1024
                nms_radius: 0
