defaults:
    - lightglue_homography
    - model@model.extractor: extractor/sift
    - _self_

model:
    extractor:
        max_num_keypoints: 1024
        force_num_keypoints: True
        trainable: False
        nms_radius: 3
    matcher:
        input_dim: 128
        add_scale_ori: True
benchmarks:
    hpatches:
        model:
          extractor:
            nms_radius: 0
