defaults:
    - data: homographies
    - model: two_view_pipeline
    - model@model.extractor: extractor/superpoint_open
    - model@model.matcher: matcher/lightglue
    - model@model.ground_truth: matcher/homography_matcher
    - train: homographies
    - _self_

model:
    extractor:
        name: extractors.superpoint_open
        force_num_keypoints: True
        trainable: False
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
