model:
    name: gluefactory.models.two_view_pipeline
    extractor:
        name: gluefactory.models.lines.wireframe
        point_extractor:
            name: gluefactory_nonfree.superpoint
            trainable: False
            dense_outputs: True
            max_num_keypoints: 2048
            force_num_keypoints: False
            detection_threshold: 0
        line_extractor:
            name: gluefactory.models.lines.lsd
            trainable: False
            max_num_lines: 512
            force_num_lines: False
            min_length: 15
        wireframe_params:
            merge_points: True
            merge_line_endpoints: True
            nms_radius: 3
    matcher:
        name: gluefactory.models.matchers.gluestick
        weights: checkpoint_GlueStick_MD  # This will download weights from internet

    # ground_truth:    # for ETH3D, comment otherwise
    #     name: gluefactory.models.matchers.depth_matcher
    #     use_lines: True

benchmarks:
    hpatches:
        eval:
            estimator: homography_est
            ransac_th: -1    # [1., 1.5, 2., 2.5, 3.]
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: poselib
            ransac_th: -1
    eth3d:
        ground_truth:
            name: gluefactory.models.matchers.depth_matcher
            use_lines: True
        eval:
            plot_methods: [ ]    # ['sp+NN', 'sp+sg', 'superpoint+lsd+gluestick']
            plot_line_methods: [ ]    # ['superpoint+lsd+gluestick', 'sp+deeplsd+gs']