defaults:
    - lightglue_homography
    - model@model.extractor: extractor/superpoint
    - _self_

model:
    extractor:
        max_num_keypoints: 512
        force_num_keypoints: True
        trainable: False