defaults:
    - lightglue_megadepth
    - model@model.extractor: extractor/superpoint_open
    - _self_

data:
    load_features:
        do: false  # enable this if you have cached predictions
        path: exports/megadepth-undist-depth-r1024_SP-open-k2048-nms3/{scene}.h5
        padding_length: 2048
        padding_fn: pad_local_features

model:
    extractor:
        max_num_keypoints: 2048
        force_num_keypoints: True
        trainable: False
        detection_threshold: -1
        nms_radius: 3